import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { eq } from "drizzle-orm";
import { companies, companyRegions, companyCategories } from "./schema";
import path from "path";
import fs from "fs";

// Ensure data directory exists
const dataDir = path.join(process.cwd(), "data");
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

const dbPath = path.join(dataDir, "beacon.db");
const sqlite = new Database(dbPath);
sqlite.pragma("foreign_keys = ON");
const db = drizzle(sqlite);

// Industry dataset - enriched with additional information
const industryCompanies = [
  {
    name: "724Solutions",
    website: "https://www.724solutions.com",
    linkedin_url: "https://linkedin.com/company/724solutions",
    hq_country: "NLD",
    hq_city: "Rotterdam",
    categories: ["VTS"],
    summary: "Maritime IT solutions provider specializing in vessel traffic services and port operations.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "Actual IT",
    website: "https://www.actualit.fi",
    linkedin_url: "https://linkedin.com/company/actual-it",
    hq_country: "FIN",
    hq_city: "Helsinki",
    categories: ["PMIS"],
    summary: "Port management information systems and digitalization solutions for maritime logistics.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "Signalis (Airbus)",
    website: "https://www.signalis.com",
    linkedin_url: "https://linkedin.com/company/signalis",
    hq_country: "DEU",
    hq_city: "Hamburg",
    categories: ["PMIS", "VTS", "CS"],
    summary: "Integrated vessel traffic, port management, and coastal surveillance systems for maritime authorities.",
    employees: "50-200",
    regions: ["EU", "AP"],
  },
  {
    name: "Amura",
    website: "https://www.amura.es",
    linkedin_url: "https://linkedin.com/company/amura",
    hq_country: "ESP",
    hq_city: "Madrid",
    categories: ["CS"],
    summary: "Coastal surveillance and maritime security solutions for defense and civil applications.",
    employees: "10-50",
    regions: ["EU", "LA"],
  },
  {
    name: "Awake.AI",
    website: "https://www.awake.ai",
    linkedin_url: "https://linkedin.com/company/awake-ai",
    hq_country: "FIN",
    hq_city: "Turku",
    categories: ["PMIS"],
    summary: "AI-powered port optimization platform for predictive berth planning and maritime logistics.",
    employees: "10-50",
    regions: ["EU", "NA"],
  },
  {
    name: "CBS Software",
    website: "https://www.cbssoftware.nl",
    linkedin_url: "https://linkedin.com/company/cbs-software",
    hq_country: "NLD",
    hq_city: "Rotterdam",
    categories: ["PMIS"],
    summary: "Port community systems and terminal operating systems for container terminals.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "Cofano",
    website: "https://www.cofano.com",
    linkedin_url: "https://linkedin.com/company/cofano-software",
    hq_country: "NLD",
    hq_city: "Rotterdam",
    categories: ["PMIS"],
    summary: "Port management software and terminal operating systems for maritime logistics.",
    employees: "50-200",
    regions: ["EU", "AP"],
  },
  {
    name: "Copas",
    website: "https://www.copas.com",
    linkedin_url: "https://linkedin.com/company/copas",
    hq_country: "ITA",
    hq_city: "Genoa",
    categories: ["PMIS"],
    summary: "Port community systems and single window solutions for maritime trade facilitation.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "CSIC Pride",
    website: "https://www.pridecvd.com",
    linkedin_url: "https://linkedin.com/company/csic-pride",
    hq_country: "CHN",
    hq_city: "Wuhan",
    categories: ["VTS"],
    summary: "Vessel traffic management systems and maritime surveillance solutions from China Shipbuilding Industry Corporation.",
    employees: "200-1000",
    regions: ["AP"],
  },
  {
    name: "DBA Group",
    website: "https://www.dbagroup.com",
    linkedin_url: "https://linkedin.com/company/dba-group",
    hq_country: "DNK",
    hq_city: "Copenhagen",
    categories: ["PMIS"],
    summary: "Port management and logistics software solutions for terminals and port authorities.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "Denbridge Marine",
    website: "https://www.denbridge.com",
    linkedin_url: "https://linkedin.com/company/denbridge-marine",
    hq_country: "GBR",
    hq_city: "London",
    categories: ["VTS"],
    summary: "Vessel traffic services and maritime domain awareness systems.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "Elman",
    website: "https://www.elman.fi",
    linkedin_url: "https://linkedin.com/company/elman-oy",
    hq_country: "FIN",
    hq_city: "Turku",
    categories: ["PMIS", "VTS", "CS"],
    summary: "Maritime automation and control systems including VTS, port management, and surveillance.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "Envision Digital",
    website: "https://www.envision-digital.com",
    linkedin_url: "https://linkedin.com/company/envision-digital",
    hq_country: "SGP",
    hq_city: "Singapore",
    categories: ["PMIS", "CS"],
    summary: "Smart port and IoT platform solutions for port operations and maritime surveillance.",
    employees: "1000-5000",
    regions: ["AP"],
  },
  {
    name: "Experion Maritime",
    website: "https://www.experion.fi",
    linkedin_url: "https://linkedin.com/company/experion-maritime",
    hq_country: "FIN",
    hq_city: "Turku",
    categories: ["PMIS"],
    summary: "Port call optimization and digital port solutions for maritime logistics.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "Frequentis",
    website: "https://www.frequentis.com",
    linkedin_url: "https://linkedin.com/company/frequentis",
    hq_country: "AUT",
    hq_city: "Vienna",
    categories: ["VTS", "CS"],
    summary: "Communication and information systems for air traffic control, VTS, and public safety.",
    employees: "1000-5000",
    regions: ["EU", "NA", "AP"],
  },
  {
    name: "Golden Trans",
    website: "https://www.goldentrans.com",
    linkedin_url: "https://linkedin.com/company/golden-trans",
    hq_country: "CHN",
    hq_city: "Shanghai",
    categories: ["VTS"],
    summary: "Vessel traffic management and maritime communication systems.",
    employees: "50-200",
    regions: ["AP"],
  },
  {
    name: "Grieg Connect",
    website: "https://www.griegconnect.com",
    linkedin_url: "https://linkedin.com/company/grieg-connect",
    hq_country: "NOR",
    hq_city: "Bergen",
    categories: ["PMIS"],
    summary: "Digital shipping and port technology solutions for vessel calls and cargo handling.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "Harbour Mastery",
    website: "https://www.harbourmastery.com",
    linkedin_url: "https://linkedin.com/company/harbour-mastery",
    hq_country: "AUS",
    hq_city: "Melbourne",
    categories: ["PMIS"],
    summary: "Marine management software for pilotage, towage, and harbour operations.",
    employees: "10-50",
    regions: ["AP"],
  },
  {
    name: "IMIS Global",
    website: "https://www.imisglobal.com",
    linkedin_url: "https://linkedin.com/company/imis-global",
    hq_country: "NLD",
    hq_city: "Rotterdam",
    categories: ["PMIS", "VTS"],
    summary: "Integrated maritime information systems for port management and vessel tracking.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "Innovative Navigation (IN)",
    website: "https://www.in-navigation.com",
    linkedin_url: "https://linkedin.com/company/innovative-navigation",
    hq_country: "NLD",
    hq_city: "Rotterdam",
    categories: ["VTS", "CS"],
    summary: "Navigation and traffic management systems for inland waterways and coastal areas.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "Indra Sistemas",
    website: "https://www.indracompany.com",
    linkedin_url: "https://linkedin.com/company/indra",
    hq_country: "ESP",
    hq_city: "Madrid",
    categories: ["PMIS", "VTS", "CS"],
    summary: "Global technology and consulting company providing VTS, port management, and defense systems.",
    employees: "5000+",
    regions: ["EU", "LA", "AP"],
  },
  {
    name: "Infoport",
    website: "https://www.infoport.be",
    linkedin_url: "https://linkedin.com/company/infoport",
    hq_country: "BEL",
    hq_city: "Antwerp",
    categories: ["PMIS"],
    summary: "Port community system for the Port of Antwerp-Bruges.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "Innovez One",
    website: "https://www.innovez.one",
    linkedin_url: "https://linkedin.com/company/innovez-one",
    hq_country: "IND",
    hq_city: "Mumbai",
    categories: ["PMIS", "CS"],
    summary: "Smart port solutions and maritime surveillance for Indian ports.",
    employees: "50-200",
    regions: ["AP"],
  },
  {
    name: "Inplan",
    website: "https://www.inplan.fi",
    linkedin_url: "https://linkedin.com/company/inplan",
    hq_country: "FIN",
    hq_city: "Helsinki",
    categories: ["PMIS"],
    summary: "Port management and logistics planning software.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "Inport",
    website: "https://www.inport.no",
    linkedin_url: "https://linkedin.com/company/inport",
    hq_country: "NOR",
    hq_city: "Oslo",
    categories: ["PMIS"],
    summary: "Digital port call and cargo handling solutions for Norwegian ports.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "Insiris",
    website: "https://www.insiris.com",
    linkedin_url: "https://linkedin.com/company/insiris",
    hq_country: "USA",
    hq_city: "Arlington",
    categories: ["CS"],
    summary: "Maritime domain awareness and coastal surveillance solutions for defense and security.",
    employees: "10-50",
    regions: ["NA"],
  },
  {
    name: "IT Partner",
    website: "https://www.itpartner.no",
    linkedin_url: "https://linkedin.com/company/it-partner",
    hq_country: "NOR",
    hq_city: "Oslo",
    categories: ["PMIS"],
    summary: "Port and terminal management systems for Scandinavian ports.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "JRC (Japan Radio Co.)",
    website: "https://www.jrc.co.jp",
    linkedin_url: "https://linkedin.com/company/japan-radio-co",
    hq_country: "JPN",
    hq_city: "Tokyo",
    categories: ["VTS"],
    summary: "Marine electronics and vessel traffic management systems manufacturer.",
    employees: "1000-5000",
    regions: ["AP"],
  },
  {
    name: "Kale Logistics",
    website: "https://www.kalelogistics.com",
    linkedin_url: "https://linkedin.com/company/kale-logistics-solutions",
    hq_country: "IND",
    hq_city: "Mumbai",
    categories: ["PMIS"],
    summary: "Port community systems and logistics solutions for cargo and container terminals.",
    employees: "200-1000",
    regions: ["AP"],
  },
  {
    name: "Kongsberg NorControl",
    website: "https://www.kongsberg.com",
    linkedin_url: "https://linkedin.com/company/kongsberg-digital",
    hq_country: "NOR",
    hq_city: "Horten",
    categories: ["PMIS", "VTS", "CS"],
    summary: "Vessel traffic management, port operations, and maritime surveillance systems.",
    employees: "1000-5000",
    regions: ["EU", "NA", "AP"],
  },
  {
    name: "Leonardo",
    website: "https://www.leonardo.com",
    linkedin_url: "https://linkedin.com/company/leonardo",
    hq_country: "ITA",
    hq_city: "Rome",
    categories: ["PMIS", "VTS", "CS"],
    summary: "Aerospace and defense company providing radar, VTS, and integrated surveillance systems.",
    employees: "5000+",
    regions: ["EU", "NA", "AP"],
  },
  {
    name: "Lockheed Martin",
    website: "https://www.lockheedmartin.com",
    linkedin_url: "https://linkedin.com/company/lockheed-martin",
    hq_country: "USA",
    hq_city: "Bethesda",
    categories: ["VTS"],
    summary: "Global aerospace and defense company with maritime traffic management solutions.",
    employees: "5000+",
    regions: ["NA"],
  },
  {
    name: "Marico Marine",
    website: "https://www.marico.co.uk",
    linkedin_url: "https://linkedin.com/company/marico-marine",
    hq_country: "GBR",
    hq_city: "North Shields",
    categories: ["PMIS", "VTS"],
    summary: "Maritime risk management, VTS, and port operations consultancy and software.",
    employees: "50-200",
    regions: ["EU"],
  },
  {
    name: "MGI-CI5",
    website: "https://www.mgi-ci5.com",
    linkedin_url: "https://linkedin.com/company/mgi-ci5",
    hq_country: "FRA",
    hq_city: "Marseille",
    categories: ["PMIS"],
    summary: "Port community systems and customs integration solutions for French ports.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "Navayuga Infotech",
    website: "https://www.navayugainfotech.com",
    linkedin_url: "https://linkedin.com/company/navayuga-infotech",
    hq_country: "IND",
    hq_city: "Hyderabad",
    categories: ["PMIS"],
    summary: "Port management and logistics software for Indian port operations.",
    employees: "200-1000",
    regions: ["AP"],
  },
  {
    name: "Navielektro",
    website: "https://www.navielektro.fi",
    linkedin_url: "https://linkedin.com/company/navielektro",
    hq_country: "FIN",
    hq_city: "Helsinki",
    categories: ["VTS", "CS"],
    summary: "Vessel traffic services and coastal surveillance solutions for Baltic and Scandinavian waters.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "Nicom Maritime",
    website: "https://www.nicom.no",
    linkedin_url: "https://linkedin.com/company/nicom-maritime",
    hq_country: "NOR",
    hq_city: "Trondheim",
    categories: ["PMIS", "CS"],
    summary: "Maritime communication and surveillance systems for port and coastal operations.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "Pilot Dispatch",
    website: "https://www.pilotdispatch.com",
    linkedin_url: "https://linkedin.com/company/pilot-dispatch",
    hq_country: "AUS",
    hq_city: "Brisbane",
    categories: ["PMIS", "PDMS", "CS"],
    summary: "Pilot dispatch management, port operations, and maritime situational awareness systems.",
    employees: "10-50",
    regions: ["AP"],
  },
  {
    name: "Polymathian",
    website: "https://www.polymathian.com",
    linkedin_url: "https://linkedin.com/company/polymathian",
    hq_country: "AUS",
    hq_city: "Melbourne",
    categories: ["PMIS", "CS"],
    summary: "AI-powered optimization platform for port operations and supply chain logistics.",
    employees: "10-50",
    regions: ["AP"],
  },
  {
    name: "PortBase",
    website: "https://www.portbase.com",
    linkedin_url: "https://linkedin.com/company/portbase",
    hq_country: "NLD",
    hq_city: "Rotterdam",
    categories: ["PCS"],
    summary: "Port community system connecting all parties in the Dutch maritime logistics chain.",
    employees: "50-200",
    regions: ["EU"],
  },
  {
    name: "Portchain",
    website: "https://www.portchain.com",
    linkedin_url: "https://linkedin.com/company/portchain",
    hq_country: "DNK",
    hq_city: "Copenhagen",
    categories: ["PMIS"],
    summary: "AI-driven container terminal optimization and berth planning software.",
    employees: "10-50",
    regions: ["EU", "NA"],
  },
  {
    name: "Portel (GTD)",
    website: "https://www.gtd.eu",
    linkedin_url: "https://linkedin.com/company/gtd",
    hq_country: "ESP",
    hq_city: "Madrid",
    categories: ["PMIS"],
    summary: "Port community systems and cargo management solutions for Spanish and Latin American ports.",
    employees: "200-1000",
    regions: ["EU", "LA"],
  },
  {
    name: "PortXchange",
    website: "https://www.portxchange.com",
    linkedin_url: "https://linkedin.com/company/portxchange",
    hq_country: "NLD",
    hq_city: "Rotterdam",
    categories: ["PMIS"],
    summary: "Port call optimization platform connecting ships, terminals, and service providers.",
    employees: "10-50",
    regions: ["EU", "NA", "AP"],
  },
  {
    name: "Prodevelop",
    website: "https://www.prodevelop.es",
    linkedin_url: "https://linkedin.com/company/prodevelop",
    hq_country: "ESP",
    hq_city: "Valencia",
    categories: ["PMIS"],
    summary: "Port community systems and smart logistics solutions.",
    employees: "50-200",
    regions: ["EU", "LA"],
  },
  {
    name: "Raytheon Technologies",
    website: "https://www.rtx.com",
    linkedin_url: "https://linkedin.com/company/raytheon-technologies",
    hq_country: "USA",
    hq_city: "Arlington",
    categories: ["VTS"],
    summary: "Defense and aerospace company with coastal surveillance and VTS solutions.",
    employees: "5000+",
    regions: ["NA"],
  },
  {
    name: "Sercel",
    website: "https://www.sercel.com",
    linkedin_url: "https://linkedin.com/company/sercel",
    hq_country: "FRA",
    hq_city: "Nantes",
    categories: ["VTS"],
    summary: "Marine acoustic and seismic equipment manufacturer with maritime surveillance products.",
    employees: "1000-5000",
    regions: ["EU"],
  },
  {
    name: "Seaport OPX",
    website: "https://www.seaportopx.com",
    linkedin_url: "https://linkedin.com/company/seaport-opx",
    hq_country: "USA",
    hq_city: "Houston",
    categories: ["PMIS"],
    summary: "Port operations excellence platform for terminal and cargo management.",
    employees: "10-50",
    regions: ["NA"],
  },
  {
    name: "Shiplogic",
    website: "https://www.shiplogic.com",
    linkedin_url: "https://linkedin.com/company/shiplogic",
    hq_country: "NLD",
    hq_city: "Rotterdam",
    categories: ["PMIS"],
    summary: "Port call optimization and berth planning software for terminals.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "SRT Marine Systems",
    website: "https://www.srt-marine.com",
    linkedin_url: "https://linkedin.com/company/srt-marine-systems",
    hq_country: "GBR",
    hq_city: "Wymondham",
    categories: ["VTS", "CS"],
    summary: "Maritime domain awareness systems including AIS and vessel tracking solutions.",
    employees: "50-200",
    regions: ["EU", "NA", "AP"],
  },
  {
    name: "Thales",
    website: "https://www.thalesgroup.com",
    linkedin_url: "https://linkedin.com/company/thales",
    hq_country: "FRA",
    hq_city: "Paris",
    categories: ["VTS"],
    summary: "Global technology company providing VTS, air traffic management, and defense systems.",
    employees: "5000+",
    regions: ["EU", "NA", "LA", "AP"],
  },
  {
    name: "TimeZero",
    website: "https://www.timezero.com",
    linkedin_url: "https://linkedin.com/company/timezero",
    hq_country: "FRA",
    hq_city: "Vannes",
    categories: ["VTS"],
    summary: "Marine navigation software and charting systems for professional maritime operations.",
    employees: "50-200",
    regions: ["EU"],
  },
  {
    name: "Unikie",
    website: "https://www.unikie.com",
    linkedin_url: "https://linkedin.com/company/unikie",
    hq_country: "FIN",
    hq_city: "Tampere",
    categories: ["PMIS"],
    summary: "Embedded systems and IoT solutions for port automation and maritime industry.",
    employees: "50-200",
    regions: ["EU"],
  },
  {
    name: "Vissim",
    website: "https://www.vissim.nl",
    linkedin_url: "https://linkedin.com/company/vissim",
    hq_country: "NLD",
    hq_city: "Rotterdam",
    categories: ["PMIS", "VTS"],
    summary: "Port simulation, VTS training, and maritime traffic optimization solutions.",
    employees: "10-50",
    regions: ["EU"],
  },
  {
    name: "Wärtsilä Voyage (PortLink)",
    website: "https://www.wartsila.com/marine/port-operations",
    linkedin_url: "https://linkedin.com/company/wartsila-voyage",
    hq_country: "FIN",
    hq_city: "Helsinki",
    categories: ["PMIS", "VTS", "CS", "PDMS"],
    summary: "Comprehensive port operations platform including VTS, PMIS, pilot dispatch, and surveillance.",
    employees: "5000+",
    regions: ["EU", "NA", "AP"],
  },
  {
    name: "Webb Fontaine",
    website: "https://www.webbfontaine.com",
    linkedin_url: "https://linkedin.com/company/webb-fontaine",
    hq_country: "ARE",
    hq_city: "Dubai",
    categories: ["PCS"],
    summary: "Customs and trade facilitation solutions with port community system capabilities.",
    employees: "1000-5000",
    regions: ["EU", "AP", "LA"],
  },
  {
    name: "Xanatos Marine",
    website: "https://www.xanatos.com",
    linkedin_url: "https://linkedin.com/company/xanatos-marine",
    hq_country: "USA",
    hq_city: "San Diego",
    categories: ["VTS"],
    summary: "Maritime surveillance and vessel traffic management systems.",
    employees: "10-50",
    regions: ["NA"],
  },
  {
    name: "XST Technologies",
    website: "https://www.xst.com.au",
    linkedin_url: "https://linkedin.com/company/xst-technologies",
    hq_country: "AUS",
    hq_city: "Sydney",
    categories: ["VTS"],
    summary: "Maritime traffic management and vessel monitoring solutions.",
    employees: "10-50",
    regions: ["AP"],
  },
  {
    name: "Yantai Huadong Electronics",
    website: "https://www.chinahdec.com",
    linkedin_url: "https://linkedin.com/company/yantai-huadong",
    hq_country: "CHN",
    hq_city: "Yantai",
    categories: ["VTS"],
    summary: "Marine electronics and vessel traffic management systems manufacturer.",
    employees: "1000-5000",
    regions: ["AP"],
  },
];

async function seedIndustryData() {
  console.log("Seeding industry dataset...");
  console.log(`Total companies to add: ${industryCompanies.length}\n`);

  let added = 0;
  let skipped = 0;

  for (const companyData of industryCompanies) {
    const { regions, categories, ...company } = companyData;

    // Check if company already exists (by name)
    const existing = db
      .select()
      .from(companies)
      .where(eq(companies.name, company.name))
      .all();

    if (existing.length > 0) {
      console.log(`  [SKIP] ${company.name} (already exists)`);
      skipped++;
      continue;
    }

    // Insert company
    const result = db.insert(companies).values(company).returning().get();

    // Insert regions
    if (regions && regions.length > 0) {
      for (const region of regions) {
        db.insert(companyRegions)
          .values({
            company_id: result.id,
            region,
          })
          .run();
      }
    }

    // Insert categories
    if (categories && categories.length > 0) {
      for (const category of categories) {
        db.insert(companyCategories)
          .values({
            company_id: result.id,
            category,
          })
          .run();
      }
    }

    console.log(`  [ADD] ${company.name}`);
    added++;
  }

  console.log(`\nSummary:`);
  console.log(`  Added: ${added} companies`);
  console.log(`  Skipped: ${skipped} companies (already exist)`);
  console.log(`  Total in dataset: ${industryCompanies.length}`);
}

seedIndustryData()
  .catch(console.error)
  .finally(() => sqlite.close());

